# Generated by Django 4.1.10 on 2023-07-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tnt",
            name="breaks",
            field=models.TimeField(verbose_name="breaks"),
        ),
    ]
