# Generated by Django 4.1.10 on 2023-07-24 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tours", "0002_chronopostpickup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chronopostdelivery",
            name="linked_user",
            field=models.ForeignKey(
                default="00000000",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deliveryman",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chronopostpickup",
            name="linked_user",
            field=models.ForeignKey(
                default="00000000",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deliveryman",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ciblex",
            name="linked_user",
            field=models.ForeignKey(
                default="00000000",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deliveryman",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gls",
            name="linked_user",
            field=models.ForeignKey(
                default="00000000",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deliveryman",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tnt",
            name="linked_user",
            field=models.ForeignKey(
                default="00000000",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deliveryman",
            ),
            preserve_default=False,
        ),
    ]
