# Generated by Django 4.1.10 on 2023-07-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0002_alter_tnt_breaks"),
    ]

    operations = [
        migrations.AddField(
            model_name="chronopost",
            name="total_hour",
            field=models.FloatField(blank=True, null=True, verbose_name="Total Hour"),
        ),
        migrations.AddField(
            model_name="ciblex",
            name="total_hour",
            field=models.FloatField(blank=True, null=True, verbose_name="Total Hour"),
        ),
        migrations.AddField(
            model_name="gls",
            name="total_hour",
            field=models.FloatField(blank=True, null=True, verbose_name="Total Hour"),
        ),
        migrations.AddField(
            model_name="tnt",
            name="total_hour",
            field=models.FloatField(blank=True, null=True, verbose_name="Total Hour"),
        ),
    ]
