# Generated by Django 4.1.10 on 2023-07-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0003_chronopostdelivery_linked_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chronopostdelivery",
            options={},
        ),
        migrations.AlterModelOptions(
            name="chronopostpickup",
            options={},
        ),
        migrations.AlterModelOptions(
            name="gls",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tnt",
            options={},
        ),
        migrations.AlterField(
            model_name="tnt",
            name="breaks",
            field=models.TimeField(verbose_name="Breaks"),
        ),
    ]
