# Generated by Django 4.1.10 on 2023-08-02 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0004_alter_chronopostdelivery_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chronopostdelivery",
            options={
                "verbose_name": "Chronopost Delivery",
                "verbose_name_plural": "Chronopost Delivery",
            },
        ),
        migrations.AlterModelOptions(
            name="chronopostpickup",
            options={
                "verbose_name": "Chronopost Pickup",
                "verbose_name_plural": "Chronopost Pickup",
            },
        ),
        migrations.AlterModelOptions(
            name="gls",
            options={"verbose_name": "GLS", "verbose_name_plural": "GLS"},
        ),
        migrations.AlterModelOptions(
            name="tnt",
            options={"verbose_name": "TNT", "verbose_name_plural": "TNT"},
        ),
        migrations.RemoveField(
            model_name="ciblex",
            name="code",
        ),
    ]
